sudo: false
language: python
cache: pip
python:
  - "3.4"
  - "2.7"
install:
  - pip install -U pip
  - pip install -r requirements-test.txt
script:
  - py.test -ra -vvv --cov
after_success:
  - bash <(curl -s https://codecov.io/bash)
